### ISSUE TITLE
How to get this to work on PyCharm?

### ISSUE THREAD

**Issue by klaasv12** [Kaggle/kaggle-environments#16]
Hi,
Probably this has been answered somewhere, but I have not been able to find it.
So my question is: is it possible to get this to work properly on pyCharm?

Regards

**Comment by janjagusch** [comment]
Hi! What do you mean with "get this to work properly on pyCharm"? Could you describe your issue a little better, please?

Usually, your IDE should not affect how this package functions. :thinking:

**Comment by klaasv12** [comment]
The code as example:
`from typing import List
import json
from kaggle_environments import make
from kaggle_environments.envs.halite.halite import get_to_pos
from kaggle_environments.utils import Struct
import pandas as pd

env = make("halite")
_ = env.reset(num_agents=4)
_ = env.run(["random", "random", "random", "random"])`

The output:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "spawn.py", line 114, in _main
    prepare(preparation_data)
  File "spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kagglehalite\halite.py", line 10, in <module>
    _ = env.run(["random", "random", "random", "random"])
  File "kagglehalite\venv\lib\site-packages\kaggle_environments\core.py", line 200, in run
    runner = self.__agent_runner(agents)
  File "kagglehalite\venv\lib\site-packages\kaggle_environments\core.py", line 550, in __agent_runner
    None else None for a in agents]
  File "kagglehalite\venv\lib\site-packages\kaggle_environments\core.py", line 550, in <listcomp>
    None else None for a in agents]
  File "kagglehalite\venv\lib\site-packages\kaggle_environments\agent.py", line 106, in __init__
    self.manager = Manager()
  File "\Python37\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "Python37\lib\multiprocessing\managers.py", line 563, in start
    self._process.start()
  File "lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.`

**Comment by klaasv12** [comment]
> Hi! What do you mean with "get this to work properly on pyCharm"? Could you describe your issue a little better, please?
> Usually, your IDE should not affect how this package functions. 🤔\

So somehow I have skipped a step somewhere I think, but really not sure where and how. The run function goes wrong.

**Comment by harrisse** [comment]
I'm not very familiar with PyCharm, but it appears that this issue happens when you have a python application that invokes multiprocessing and then you try and build that application as a Windows executable (https://kite.com/python/docs/multiprocessing.freeze_support).  It seems likely that PyCharm is configured to produce a Windows binary rather than interpreting your python code directly. You'll need to poke around PyCharm to figure out how to switch the build mode, or just develop your code in PyCharm and invoke it from the command line with the python interpreter. I'm going to close this issue out for now as we don't intend for this library to be built as a Windows executable, but if you still have trouble interpreting your code directly please reopen this issue.
